<?php
// Generated by Zend Framework 2
return array(
    'DbuBackend\Controller\BackendController' => __DIR__ . '//src/DbuBackend/Controller/BackendController.php',
    'DbuBackend\Model\User'                   => __DIR__ . '//src/DbuBackend/Model/User.php',
    'DbuBackend\Module'                       => __DIR__ . '//Module.php',
    'DbuBackendTest\Bootstrap'                => __DIR__ . '//test/Bootstrap.php',
    'DbuBackendTest\Model\UserTest'           => __DIR__ . '//test/DbuBackendTest/Model/UserTest.php',
);