<form method="post" action="<?= $url ?>">
    <label for="login_login">Login:</label>
    <input type="text" name="login" id="login_login" placeholder="enter your login" /><br />
    <label for="login_password">Password:</label>
    <input type="password" name="password" id="login_password" placeholder="enter your password" /><br />
    <input type="checkbox" name="remember" id="login_remember" />
    <label for="login_remember">Remember me</label>
    <input type="submit" value="login"/><br />
</form>
